# Rust formatting configuration for consistent code style
edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
# Note: The following options require nightly Rust and are commented out for stable compatibility:
# imports_granularity = "Module"
# group_imports = "StdExternalCrate" 
# reorder_impl_items = true
# format_code_in_doc_comments = true
# format_strings = true
# format_macro_matchers = true
